[package]
name = "fontmerge"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
license = "MIT OR Apache-2.0"
description = "Merge two font source files, copying glyphs and OpenType layout features from one font to another"
readme = "README.md"
repository = "https://github.com/simoncozens/babelfont-rs"
documentation = "https://docs.rs/fontmerge"
keywords = ["fonts", "typography", "merge", "opentype", "font-tools"]
categories = ["command-line-utilities", "text-processing"]

[[bin]]
name = "fontmerge"
path = "src/main.rs"

[[bin]]
name = "fontsubset"
path = "src/fontsubset.rs"

[dependencies]
babelfont = { version = "0.2.1", path = "../babelfont" }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
clap-verbosity-flag = "3.0.4"
fontdrasil = { workspace = true }
regex = { workspace = true }
itertools = "0.14.0"
indicatif = "0.18.2"
log-once = "0.4.1"
uuid = "1.18.1"
fea-rs-ast = { workspace = true }

[lints.clippy]
unwrap_used = "deny"
indexing_slicing = "deny"
