[package]
name = "sr-aef"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
license = "MIT OR Apache-2.0"
description = "Uncompile OpenType fonts back into Adobe feature file (fea) source code"
readme = "README.md"
repository = "https://github.com/simoncozens/babelfont-rs"
documentation = "https://docs.rs/sr-aef"
keywords = ["fonts", "opentype", "typography", "fea", "ttf"]
categories = ["text-processing", "parser-implementations"]

[[bin]]
name = "sr-aef"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = []
cli = [
    "dep:serde",
    "dep:serde_json",
    "dep:clap",
    "smol_str/serde",
    "fea-rs-ast/serde",
    "indexmap/serde",
]

[dependencies]
serde = { version = "1.0", optional = true }
fea-rs-ast = { workspace = true }
indexmap.workspace = true
skrifa = { workspace = true }
smol_str = "0.3.6"
serde_json = { version = "1.0", optional = true }
clap = { workspace = true, optional = true, features = ["derive"] }
fontdrasil.workspace = true
